# Stage 1: Build the Go app
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

COPY . .

RUN go build -o leader ./cmd/leader

FROM alpine:latest

WORKDIR /

COPY --from=builder /app/leader .

EXPOSE 8080

ENTRYPOINT ["./leader"]

CMD ["8080", "http://localhost:8081"]